language: node_js
node_js:
  - "stable"
services:
  - 'docker'
script:
  - npm install
  - npm run lint
  - npm run flow
  - npm run coverage
build:
  - './build_docker.sh'
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
    docker push ilearnttoday/bloguserinterface:tagname ;
    fi
