language: node_js
node_js:
  - "stable"
services:
  - 'docker'
script:
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
    npm install;
    npm run lint;
    npm run flow;
    npm run coverage;
    fi
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    bash ./build_docker.sh;
    fi
branches:
  only:
    - master
notifications:
  slack: ilearnttoday:G3jmA5xbV126snb6RWgg6Ywg
