language: node_js
node_js:
  - "stable"
services:
  - 'docker'
script:
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
    npm install;
    npm run lint;
    npm run flow;
    npm run coverage;
    fi
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    bash ./build_docker.sh;
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
    docker push ilearnttoday/bloguserinterface:tagname ;
    fi
